#!/bin/bash

if [ "$#" -eq 0 ]
then
      echo "Usage: git-pull <remote branch> <optional: remote>"
else
    export COMMIT_SAVE=false
    export COMMIT_MESSAGE="merge $1"

    if [ "$#" -eq 1 ]
    then
        git pull origin $1

    else
        git pull $2 $1
    fi
fi
