#!/bin/bash

export COMMIT_SAVE=false
export CUSTOM_GIT=true
export COMMIT_MESSAGE=$1

v=$(git status)
IFS="/" read -ra RESAR <<< "$v"
v="${RESAR[1]}"
IFS="-" read -ra RESAR <<< "$v"
v="${RESAR[0]}-${RESAR[1]} "

if [ $v != "-" ]; then
    git commit
else
    echo "You might have set up your branch incorrectly!"
fi

export CUSTOM_GIT=false

