#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

v=$(git status)
IFS="/" read -ra RESAR <<< "$v"
v="${RESAR[1]}"
IFS="-" read -ra RESAR <<< "$v"
v="${RESAR[0]}-${RESAR[1]} "

if [ $COMMIT_SAVE == "true" ]; then
    # amend commit
    echo $(git log -1 --pretty=%B) > $COMMIT_MSG_FILE
elif [ $v != "-" ]; then
    # normal commit
    echo $v $COMMIT_MESSAGE > $COMMIT_MSG_FILE
elif [ $CUSTOM_GIT == "true" ]; then
    printf "\n\nIf you're seeing this you probably didn't set up your branch properly!" > $COMMIT_MSG_FILE
fi

