#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

REGEXP="\b(describe|it)\.only"
CULPRITS=$(git diff-index --name-only --cached -G$REGEXP $against)
if [ ! -z "$CULPRITS" ] ; then
  cat <<EOF
Error: You are attempting to commit files that have 'describe.only' or 'it.only'

$CULPRITS

EOF
	exit 1
fi
