#!/bin/bash

if [ -z "$1" ]
then
      echo "Usage: git-commit-m <commit message>"
      exit
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" = "master" ] || [ "$current_branch" = "main" ]
then
      echo "Error: cannot commit directly to $current_branch"
      exit 1
fi

v=$(git status)
IFS=" " read -ra RESAR <<< "$v"
v="${RESAR[2]}"
IFS="-" read -ra RESAR <<< "$v"
v="${RESAR[0]}-${RESAR[1]}"

git commit -m "$v $1" 