#!/bin/bash

if [ -z "$1" ]
then
      echo "Usage: offline <service name>"
      exit
fi

AWS_PROFILE=perkhero node inspect ../../node_modules/.bin/serverless offline --noTimeout --clientName perkhero --appRegion us --stage prod --userPoolId us-east-1_giR8f8qRP --awsRegion us-east-1 --accountId 118104133007 --apiDomain perkhero.us --apiName $1
