#!/bin/sh

COMMIT_FILE=$1
COMMIT_MSG=$(cat $1)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
JIRA_ID=$(echo "$CURRENT_BRANCH" | grep -Eo "[A-Z0-9]{1,10}-?[A-Z0-9]+-\d+")

if [[ $CURRENT_BRANCH =~ ^test-.* ]]; then
    echo "Branch starts with test-, don't do anything"
else
    if [ ! -z "$JIRA_ID" ]; then
        COMMIT_MSG="$JIRA_ID $COMMIT_MSG"
        echo "$COMMIT_MSG" > $COMMIT_FILE
        echo "JIRA ID '$JIRA_ID', matched in current branch name, prepended to commit message. (Use --no-verify to skip)"
    fi

    JIRA_ID=$(echo "$COMMIT_MSG" | grep -Eo "^[A-Z0-9]{1,10}-?[A-Z0-9]+-\d+\s+")
  if [ -z "$JIRA_ID" ]; then
cat <<EOF
    Error: Commit messages should start with a JIRA ticket
        number (e.g. MAIN-123) followed by at least one
        white space.

EOF
	  exit 1
  fi
fi

