#!/bin/bash

dirs=()
while IFS=  read -r -d $'\0'; do
    dirs+=("$REPLY")
done < <(find ~/Scripts -print0)

for i in "${dirs[@]}"
do
    if  [[ $i != *'.git'* ]] && [[ $i != *'.idea'* ]]; then
        echo $i
    fi
done