#!/bin/bash

# Create work directory

month=$(date +"%B")
date=$(date +"%d")
dir=$month$date
echo Creating directory $dir

notes="Notes"$dir".txt"
echo Creating $notes

days="/Users/mason.pimentel/Google Drive/My Drive/Work/Days/"

mkdir "$days$dir"
touch "$days$dir/$notes"
echo $(date +"%A") > "$days$dir/$notes"
printf "\n" >> "$days$dir/$notes"