#!/bin/bash

# run this to create day directory in OneDrive

month=$(date +"%B")
date=$(date +"%d")
dir=$month$date
echo Creating directory $dir

notes="Notes"$dir".txt"
echo Creating $notes

days="/Users/masonp/GoogleDrive/OneDrive/Work/Days/"

mkdir $days$dir
touch $days$dir/$notes

echo $(date +"%A") > $days$dir/$notes
printf "\n" >> $days$dir/$notes